### PR TITLE
Update to stretch

### PR DESCRIPTION
**Pull request by rhysyngsun**
Upgrades the docker python version to stretch so the project can actually be built when first generated.

Tests should pass

### CODE REVIEW

**Comment by rhysyngsun** [comment]
@tasawernawaz I had to make a few more tweaks to get the tests to pass, including upgrading some dependencies, could you review again?

**Comment by rhysyngsun** [comment]
@tasawernawaz I think I ran into similar but different issues, various upgrades of `pip`, `pip-tools`, and `setuptools` I think resolved it

**Comment by tasawernawaz** [comment]
@rhysyngsun can we mentioned those versions in this PR, to avoid future issues.

**Comment by noisecapella** [comment]
@rhysyngsun Can this be merged?

**Pull request merged**
