### PR TITLE
Remove pip from apt.txt, this gets installed separately

### PR DESCRIPTION
**Pull request by noisecapella**

### CODE REVIEW

**Comment by bdero** [comment]
Why is pip actually getting installed like this and not with `apt.txt`? https://github.com/mitodl/cookiecutter-djangoapp/blob/master/%7B%7B%20cookiecutter.project_name%20%7D%7D/Dockerfile#L15-L16

**Comment by noisecapella** [comment]
The version in apt.txt is old

**Comment by noisecapella** [comment]
To be more specific, the old version was a cause in the requests installation problem here: https://github.com/mitodl/teachersportal/issues/251

**Comment by bdero** [comment]
Ah, ok. :+1:

**Pull request merged**
